-- Migration: Remove EMAIL and change USERNAME type
CREATE TABLE SCIA_TEST_DB.PUBLIC.USERS
 (
    USER_ID INT PRIMARY KEY,
    USERNAME TEXT NOT NULL,
    CREATED_AT TIMESTAMP
);

alter TABLE SCIA_TEST_DB.PUBLIC.USERS ADD COLUMN EMAIL VARCHAR(255);
alter table SCIA_TEST_DB.PUBLIC.USERS drop column CREATED_AT;
alter table SCIA_TEST_DB.PUBLIC.USERS modify column USERNAME VARCHAR(255);
alter table SCIA_TEST_DB.PUBLIC.USERS drop column EMAIL;